image: docker:stable

# services:
#   - mysql:5.7.22

stages:
  - build
  - test
  - deploy

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA
  DOCKER_DRIVER: overlay2
  MYSQL_DATABASE: test
  MYSQL_ROOT_PASSWORD: mysql_strong_password
  RAILS_ENV: test

before_script:
  - docker info
  # - apk --update add --no-cache curl py-pip
  # - pip install docker-compose

build:
  stage: build
  script:
    - docker build -t $CONTAINER_IMAGE .

test:
  stage: test
  script:
    # - docker run -i --rm $CONTAINER_IMAGE bash -c "rake db:migrate db:seed"
    - docker run -i --rm $CONTAINER_IMAGE bash -c "rake routes"

deploy:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CONTAINER_IMAGE
  only:
    - master
