image: docker:stable

stages:
  - build
  - test
  - deploy

variables:
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA
  DOCKER_DRIVER: overlay2
  RAILS_ENV: test

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t $CONTAINER_IMAGE .

test:
  stage: test
  script:
    - docker run -i --rm $CONTAINER_IMAGE bash -c "rake routes"
    # - docker run -i --rm $CONTAINER_IMAGE bash -c "rake db:migrate db:seed"
    # - docker run -i --name $CI_COMMIT_SHA $CONTAINER_IMAGE bash -c "rake docs:generate"
    # - docker commit -a "Gitlab CI" -m "Docs generation" $CI_COMMIT_SHA $CONTAINER_IMAGE
    # - docker rm -vf $CI_COMMIT_SHA

deploy:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CONTAINER_IMAGE
    - docker tag $CONTAINER_IMAGE $CI_REGISTRY/$CI_PROJECT_PATH:latest
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:latest
  only:
    - master
