version: '2'
services:
  mysql:
    image: mysql
    restart: "no"
    environment:
      - MYSQL_ROOT_PASSWORD=asdf
    volumes:
      - ./mysql:/var/lib/mysql

  rails:
    image: aaron/rails
    build: .
    restart: "no"
    user: "root"
    environment:
      - RAILS_ENV=development
    links:
      - mysql:mysql
    volumes:
      - .:/src
    ports:
      - 3000/tcp

  pma:
    image: phpmyadmin/phpmyadmin
    restart: "no"
    ports:
      - 80/tcp
    links:
      - mysql:db
