version: '2'
services:
  mysql:
    image: mysql:5.7.22
    restart: "no"
    environment:
      - MYSQL_ROOT_PASSWORD=asdf
    volumes:
      - ./mysql:/var/lib/mysql

  rails:
    image: reg.thecovrigs.net/acovrig/recipes:latest
    build: .
    restart: "no"
    user: "root"
    environment:
      - RAILS_ENV=development
    links:
      - mysql:mysql
    volumes:
      - .:/src
    ports:
      - 3000:3000

  pma:
    image: phpmyadmin/phpmyadmin
    restart: "no"
    ports:
      - 8080:80/tcp
    links:
      - mysql:db
